# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# YAML-mode dashboards (editable via files)
lovelace:
  mode: storage
  dashboards:
    lovelace-offgrid:
      mode: yaml
      filename: lovelace/dashboard.yaml
      title: Off-Grid
      icon: mdi:solar-power-variant
      show_in_sidebar: true

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
timer: !include timer.yaml
template: !include templates.yaml
sensor: !include sensors.yaml
utility_meter: !include utility_meter.yaml

mqtt: !include mqtt_dvcc.yaml

template:
  - trigger:
      - trigger: event
        event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        icon: "mdi:puzzle"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"
